import naivasha from "../../assets/images/naivasha.jpg";
import nairobi from "../../assets/images/nairobi (2).jpg";
import mara from "../../assets/images/Mara.jpg";
import mombasa from "../../assets/images/mombasa.jpg";
import hero from "../../assets/images/hero.jpg";

const trips = [
  {
    id: 1,
    title: "Weekend in Naivasha",
    image: naivasha,
    days: 3,
    budget: "KES 25,000",
    highlights: [
      "Hell's Gate",
      "Crescent Island",
      "Boat Ride"
    ]
  },

  {
    id: 2,
    title: "Diani Escape",
    image: hero,
    days: 5,
    budget: "KES 32,000",
    highlights: [
      "Beach Walk",
      "Snorkeling",
      "Resort Stay"
    ]
  },

  {
    id: 3,
    title: "Maasai Mara Safari",
    image: mara,
    days: 4,
    budget: "KES 75,000",
    highlights: [
      "Game Drive",
      "Luxury Camp",
      "Safari Tour"
    ]
  },
  {
    id: 4,
    title: "Nairobi City Break",
    image: nairobi,
    days: 2,
    budget: "KES 15,000",
    highlights: [
      "City Tour",
      "Shopping",
      "Cultural Experience"
    ]
  },
  {
    id: 5,
    title: "Mombasa Coastal Getaway",
    image: mombasa,
    days: 6,
    budget: "KES 45,000",
    highlights: [
      "Beach Relaxation",
      "Snorkeling",
      "Local Cuisine"
    ]
  }
];

function ExampleTrips() {
  return (
    <section className="bg-slate-50 py-24">

      <div className="mx-auto max-w-7xl px-6">

        <div className="text-center">

          <h2 className="text-4xl font-bold text-slate-900">

            Explore Example Trips

          </h2>

          <p className="mt-4 text-slate-600">

            Discover itineraries generated by TravelGen AI.

          </p>

        </div>

        <div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-3">

          {trips.map((trip) => (

            <div
              key={trip.id}
              className="overflow-hidden rounded-3xl bg-white shadow-md transition duration-300 hover:-translate-y-2 hover:shadow-2xl"
            >

              <img
                src={trip.image}
                alt={trip.title}
                className="h-64 w-full object-cover"
              />

              <div className="p-6">

                <h3 className="text-2xl font-semibold">

                  {trip.title}

                </h3>

                <div className="mt-3 flex gap-4 text-sm text-slate-500">

                  <span>

                    {trip.days} Days

                  </span>

                  <span>

                    {trip.budget}

                  </span>

                </div>

                <ul className="mt-5 space-y-2">

                  {trip.highlights.map((highlight) => (

                    <li
                      key={highlight}
                      className="text-slate-600"
                    >

                      • {highlight}

                    </li>

                  ))}

                </ul>

                <button
                  className="mt-6 rounded-xl bg-green-700 px-5 py-3 text-white transition hover:bg-green-800"
                >

                  Explore Trip

                </button>

              </div>

            </div>

          ))}

        </div>

      </div>

    </section>
  );
}

export default ExampleTrips;