import { Link } from "react-router-dom";

const cloud =
  "https://res.cloudinary.com/dxemxzh3/image/upload/w_768,h_512,c_fill,q_auto,f_auto";

const Naivasha = `${cloud}/Naivasha`;
const nairobi = `${cloud}/nairobi`;
const Mara = `${cloud}/Mara`;
const mombasa = `${cloud}/mombasa`;
const hero = `${cloud}/hero`;

const trips = [
  {
    id: 1,
    title: "Weekend in Naivasha",
    destination: "Naivasha",
    image: Naivasha,
    days: 3,
    budget: "KES 25,000",
    highlights: ["Hell's Gate", "Crescent Island", "Boat Ride"],
  },

  {
    id: 2,
    title: "Diani Escape",
    destination: "Diani",
    image: hero,
    days: 5,
    budget: "KES 32,000",
    highlights: ["Beach Walk", "Snorkeling", "Resort Stay"],
  },

  {
    id: 3,
    title: "Maasai Mara Safari",
    destination: "Maasai Mara",
    image: Mara,
    days: 4,
    budget: "KES 75,000",
    highlights: ["Game Drive", "Luxury Camp", "Safari Tour"],
  },

  {
    id: 4,
    title: "Nairobi City Break",
    destination: "Nairobi",
    image: nairobi,
    days: 2,
    budget: "KES 15,000",
    highlights: ["City Tour", "Shopping", "Cultural Experience"],
  },

  {
    id: 5,
    title: "Mombasa Coastal Getaway",
    destination: "Mombasa",
    image: mombasa,
    days: 6,
    budget: "KES 45,000",
    highlights: ["Beach Relaxation", "Snorkeling", "Local Cuisine"],
  },
];

const featuredTrips = trips.slice(0, 3);

function ExampleTrips() {
  return (
    <section className="bg-[var(--color-surface-soft)] py-16 sm:py-20">
      <div className="mx-auto max-w-7xl px-6">
        <div className="text-center">
          <h2 className="text-4xl font-bold text-[var(--color-text)]">
            Explore Example Trips
          </h2>

          <p className="mt-4 text-[var(--color-text-secondary)]">
            Discover itineraries generated by TravelGen AI.
          </p>
        </div>

        <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {featuredTrips.map((trip) => (
            <article
              key={trip.id}
              className="overflow-hidden rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] shadow-[var(--shadow-soft)] transition duration-300 hover:-translate-y-1 hover:shadow-[var(--shadow-card)]"
            >
              <img
                src={trip.image}
                alt={trip.title}
                className="h-48 w-full object-cover sm:h-52"
              />

              <div className="p-5">
                <h3 className="text-xl font-semibold text-[var(--color-text)]">
                  {trip.title}
                </h3>

                <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-sm text-[var(--color-text-muted)]">
                  <span>{trip.days} Days</span>
                  <span>{trip.budget}</span>
                </div>

                <Link
                  to={`/planner?destination=${encodeURIComponent(
                    trip.destination
                  )}`}
                  className="mt-5 inline-flex items-center justify-center rounded-xl bg-[var(--color-primary)] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[var(--color-primary-dark)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-light)] focus:ring-offset-2"
                >
                  Explore Trip
                </Link>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}

export default ExampleTrips;